
TULEM = tulem.exe

build:
	ocamlc graphics.cma Struktuurid.ml AlgoBaas.ml Laiuti.ml SygavutiEes.ml SygavutiLopp.ml Prim.ml Kruskal.ml Dijkstra.ml FloydWarshall.ml TopoKahn.ml TopoLopp.ml Eeldusgraaf.ml Kosaraju.ml Projekt.ml -o $(TULEM)

clean:
	rm -f $(TULEM)
	rm -f *.cmi
	rm -f *.cmo
