
TULEM = tulem.exe

build:
	ocamlc graphics.cma str.cma Struktuurid.ml AlgoBaas.ml Laiuti.ml SygavutiEes.ml SygavutiLopp.ml Prim.ml Kruskal.ml Dijkstra.ml FloydWarshall.ml TopoKahn.ml TopoLopp.ml Eeldusgraaf.ml Kosaraju.ml Graafika.ml NtGraafid.ml MetaPost.ml Programm.ml -o $(TULEM)

clean:
	rm -f $(TULEM)
	rm -f *.cmi
	rm -f *.cmo
	rm -f *.log
	rm -f *.pdf
	rm -f *.mp*
	rm -f temp.*
	rm -f *.1
